<?php

session_start();

$isLoggedIn = isset($_SESSION["user_id"]);
$username = $isLoggedIn ? $_SESSION["username"] : null;
$role = $isLoggedIn ? $_SESSION["role"] : null;

?>

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Cart — Mang Inasal</title>

    <link rel="stylesheet" href="style.css">

</head>

<body>

<header>

    <div class="nav-container">

        <a href="index.php" class="logo">
            <img src="images/mang-inasal-logo.png" alt="Mang Inasal">
        </a>

        <nav>

            <a href="index.php">Home</a>

            <a href="mainCourse.php">Menu</a>

            <a href="drinks.php">Drinks</a>

            <a href="dessert.php">Dessert</a>

            <a href="cart.php" class="active">
                Cart
                <span id="cart-count">0</span>
            </a>

            <?php if ($isLoggedIn): ?>

                <?php if ($role === "admin"): ?>

                    <a href="admin/dashboard.php">
                        <?= htmlspecialchars($username) ?>
                    </a>

                <?php elseif ($role === "staff"): ?>

                    <a href="staff/dashboard.php">
                        <?= htmlspecialchars($username) ?>
                    </a>

                <?php else: ?>

                    <a href="customer/dashboard.php">
                        <?= htmlspecialchars($username) ?>
                    </a>

                <?php endif; ?>

                <a href="logout.php">Logout</a>

            <?php else: ?>

                <a href="login.php">Login</a>

            <?php endif; ?>

        </nav>

    </div>

</header>


<main class="cart-page">

    <div class="cart-container">

        <h1>Your Cart</h1>

        <div id="cart-items">

            <!-- Cart items are generated by script.js -->

        </div>


        <div class="cart-summary">

            <div class="summary-row">

                <span>Subtotal</span>

                <span id="subtotal">
                    ₱0.00
                </span>

            </div>


            <div class="summary-row">

                <span>Items</span>

                <span id="item-count">
                    0
                </span>

            </div>


            <div class="summary-row">

                <span>Senior Citizen Discount</span>

                <span id="senior-discount">
                    ₱0.00
                </span>

            </div>


            <div class="summary-row">

                <span>Shipping</span>

                <span id="shipping">
                    ₱50.00
                </span>

            </div>


            <hr>


            <div class="summary-row total-row">

                <strong>Total</strong>

                <strong id="total">
                    ₱0.00
                </strong>

            </div>


            <button
                id="checkout-btn"
                class="checkout-btn"
                type="button"
            >
                Checkout
            </button>

        </div>

    </div>

</main>


<!-- RECEIPT MODAL -->

<div
    id="receipt-modal"
    class="receipt-modal"
    style="display: none;"
>

    <div class="receipt-content">

        <button
            id="close-receipt"
            class="close-receipt"
            type="button"
        >
            &times;
        </button>

        <h2>Order Receipt</h2>

        <div id="receipt-items"></div>

        <div class="receipt-total">

            <strong>Total:</strong>

            <span id="receipt-total">
                ₱0.00
            </span>

        </div>

        <button
            id="finalize-order"
            class="checkout-btn"
            type="button"
        >
            Confirm Order
        </button>

    </div>

</div>


<script src="script.js"></script>

</body>

</html>